//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace mtaulty { namespace AJHoloServer {

public interface class IAJHoloServerConsumer
{
    event Windows::Foundation::TypedEventHandler<AJHoloServerConsumer^, Platform::Object^>^ DeviceConnectedCountChanged;
};

public ref class AJHoloServerConsumer sealed  : [Windows::Foundation::Metadata::Default] IAJHoloServerConsumer, ISignalEmitter
{
public:
    AJHoloServerConsumer(Windows::Devices::AllJoyn::AllJoynBusAttachment^ busAttachment);
    virtual ~AJHoloServerConsumer();

    // Create a consumer from a device Id asynchronously.
    //
    // This is usually called to create a consumer after the unique name of a producer has been reported
    // in the Added callback on the DeviceWatcher.
    static Windows::Foundation::IAsyncOperation<AJHoloServerConsumer^>^ FromIdAsync(_In_ Platform::String^ deviceId);

    // Create a consumer from a device Id asynchronously with the provided bus attachment.
    //
    // This is usually called to create a consumer after the unique name of a producer has been reported
    // in the Added callback on the DeviceWatcher.
    static Windows::Foundation::IAsyncOperation<AJHoloServerConsumer^>^ FromIdAsync(_In_ Platform::String^ deviceId, _In_ Windows::Devices::AllJoyn::AllJoynBusAttachment^ busAttachment);

    int32 AJHoloServerConsumer::Initialize(_In_ Windows::Devices::AllJoyn::AllJoynServiceInfo^ serviceInfo);

    // Call the AddWorldAnchor method
    Windows::Foundation::IAsyncOperation<AJHoloServerAddWorldAnchorResult^>^ AddWorldAnchorAsync(_In_ Platform::String^ interfaceMemberAnchorId, _In_ uint32 interfaceMemberByteStart, _In_ uint32 interfaceMemberByteLength, _In_ bool interfaceMemberLastBlock, _In_ Windows::Foundation::Collections::IVectorView<byte>^ interfaceMemberAnchorData);
    // Call the AddHologramToAnchor method
    Windows::Foundation::IAsyncOperation<AJHoloServerAddHologramToAnchorResult^>^ AddHologramToAnchorAsync(_In_ Platform::String^ interfaceMemberAnchorId, _In_ Platform::String^ interfaceMemberHoloId, _In_ Platform::String^ interfaceMemberHoloTypeName, _In_ AJHoloServerPosition^ interfaceMemberPosition);
    // Call the RemoveHologram method
    Windows::Foundation::IAsyncOperation<AJHoloServerRemoveHologramResult^>^ RemoveHologramAsync(_In_ Platform::String^ interfaceMemberHoloId);
    // Call the GetWorldAnchor method
    Windows::Foundation::IAsyncOperation<AJHoloServerGetWorldAnchorResult^>^ GetWorldAnchorAsync(_In_ Platform::String^ interfaceMemberAnchorId, _In_ uint32 interfaceMemberByteIndex, _In_ uint32 interfaceMemberByteLength);
    // Call the GetWorldAnchorIds method
    Windows::Foundation::IAsyncOperation<AJHoloServerGetWorldAnchorIdsResult^>^ GetWorldAnchorIdsAsync();
    // Call the GetHologramIdsAndNames method
    Windows::Foundation::IAsyncOperation<AJHoloServerGetHologramIdsAndNamesResult^>^ GetHologramIdsAndNamesAsync();
    // Call the GetHologramTransforms method
    Windows::Foundation::IAsyncOperation<AJHoloServerGetHologramTransformsResult^>^ GetHologramTransformsAsync();

    // This event fires whenever the value of DeviceConnectedCount changes.
    virtual event Windows::Foundation::TypedEventHandler<AJHoloServerConsumer^, Platform::Object^>^ DeviceConnectedCountChanged 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<AJHoloServerConsumer^, Platform::Object^>^ handler) 
        { 
            return _DeviceConnectedCountChanged += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<AJHoloServerConsumer^>(sender), safe_cast<Platform::Object^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _DeviceConnectedCountChanged -= token; 
        } 
    internal: 
        void raise(AJHoloServerConsumer^ sender, Platform::Object^ args) 
        { 
            _DeviceConnectedCountChanged(sender, args);
        } 
    }

    // Get the value of the DeviceConnectedCount property.
    Windows::Foundation::IAsyncOperation<AJHoloServerGetDeviceConnectedCountResult^>^ GetDeviceConnectedCountAsync();


    // Used to send signals or register functions to handle received signals.
    property AJHoloServerSignals^ Signals
    {
        AJHoloServerSignals^ get() { return m_signals; }
    }

    // Used to get the name of the interface this consumer implements.
    static property Platform::String^ InterfaceName
    {
        Platform::String^ get() { return AllJoynHelpers::MultibyteToPlatformString(m_interfaceName); }
    }

    virtual property Windows::Devices::AllJoyn::AllJoynBusObject^ BusObject
    {
        Windows::Devices::AllJoyn::AllJoynBusObject^ get() { return m_busObject; }
    }

    virtual property Windows::Devices::AllJoyn::AllJoynSession^ Session
    {
        Windows::Devices::AllJoyn::AllJoynSession^ get() { return m_session; }
    }

internal:
    // Consumers do not support property get.
    QStatus OnPropertyGet(_In_ PCSTR interfaceName, _In_ PCSTR propertyName, _Inout_ alljoyn_msgarg val)
    {
        UNREFERENCED_PARAMETER(interfaceName); UNREFERENCED_PARAMETER(propertyName); UNREFERENCED_PARAMETER(val);
        return ER_NOT_IMPLEMENTED;
    }

    // Consumers do not support property set.
    QStatus OnPropertySet(_In_ PCSTR interfaceName, _In_ PCSTR propertyName, _In_ alljoyn_msgarg val)
    {
        UNREFERENCED_PARAMETER(interfaceName); UNREFERENCED_PARAMETER(propertyName); UNREFERENCED_PARAMETER(val);
        return ER_NOT_IMPLEMENTED;
    }

    void OnPropertyChanged(_In_ alljoyn_proxybusobject obj, _In_ PCSTR interfaceName, _In_ const alljoyn_msgarg changed, _In_ const alljoyn_msgarg invalidated);

    property Platform::String^ ServiceObjectPath
    {
        Platform::String^ get() { return m_ServiceObjectPath; }
        void set(Platform::String^ value) { m_ServiceObjectPath = value; }
    }

    property alljoyn_proxybusobject ProxyBusObject
    {
        alljoyn_proxybusobject get() { return m_proxyBusObject; }
        void set(alljoyn_proxybusobject value) { m_proxyBusObject = value; }
    }

private:
    virtual event Windows::Foundation::EventHandler<Platform::Object^>^ _SessionLost;
    virtual event Windows::Foundation::EventHandler<Platform::Object^>^ _SessionMemberAdded;
    virtual event Windows::Foundation::EventHandler<Platform::Object^>^ _SessionMemberRemoved;
    virtual event Windows::Foundation::EventHandler<Platform::Object^>^ _DeviceConnectedCountChanged;

    // Register a callback function to handle incoming signals.
    QStatus AddSignalHandler(_In_ alljoyn_busattachment busAttachment, _In_ alljoyn_interfacedescription interfaceDescription, _In_ PCSTR methodName, _In_ alljoyn_messagereceiver_signalhandler_ptr handler);

    static void CallWorldAnchorAddedSignalHandler(_In_ const alljoyn_interfacedescription_member* member, _In_ alljoyn_message message);
    static void CallHologramAddedSignalHandler(_In_ const alljoyn_interfacedescription_member* member, _In_ alljoyn_message message);
    static void CallHologramRemovedSignalHandler(_In_ const alljoyn_interfacedescription_member* member, _In_ alljoyn_message message);

    Windows::Devices::AllJoyn::AllJoynBusAttachment^ m_busAttachment;
    Windows::Devices::AllJoyn::AllJoynBusObject^ m_busObject;
    Windows::Devices::AllJoyn::AllJoynSession^ m_session;
    AJHoloServerSignals^ m_signals;
    Platform::String^ m_ServiceObjectPath;

    alljoyn_proxybusobject m_proxyBusObject;
    alljoyn_sessionlistener m_sessionListener;
    alljoyn_busobject m_nativeBusObject;
    alljoyn_busattachment m_nativeBusAttachment;

    // Used to pass a pointer to this class to callbacks
    Platform::WeakReference* m_weak;

    // This map is required because we need a way to pass the consumer to the signal
    // handlers, but the current AllJoyn C API does not allow passing a context to these
    // callbacks.
    static std::map<alljoyn_interfacedescription, Platform::WeakReference*> SourceInterfaces;

    // The name of the interface this consumer implements.
    static PCSTR m_interfaceName;
};

} } } 
