//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::Devices::AllJoyn;
using namespace com::mtaulty::AJHoloServer;

// Note: Unlike an Interface implementation, which provides a single handler for each member, the event
// model allows for 0 or more listeners to be registered. The EventAdapter implementation deals with this
// difference by implementing a last-writer-wins policy. The lack of any return value (i.e., 0 listeners)
// is handled by returning a null result.

// Methods
IAsyncOperation<AJHoloServerAddWorldAnchorResult^>^ AJHoloServerServiceEventAdapter::AddWorldAnchorAsync(_In_ AllJoynMessageInfo^ info, _In_ Platform::String^ interfaceMemberAnchorId, _In_ uint32 interfaceMemberByteStart, _In_ uint32 interfaceMemberByteLength, _In_ bool interfaceMemberLastBlock, _In_ Windows::Foundation::Collections::IVectorView<byte>^ interfaceMemberAnchorData)
{
    auto args = ref new AJHoloServerAddWorldAnchorCalledEventArgs(info, interfaceMemberAnchorId, interfaceMemberByteStart, interfaceMemberByteLength, interfaceMemberLastBlock, interfaceMemberAnchorData);
    AddWorldAnchorCalled(this, args);
    return AJHoloServerAddWorldAnchorCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<AJHoloServerAddHologramToAnchorResult^>^ AJHoloServerServiceEventAdapter::AddHologramToAnchorAsync(_In_ AllJoynMessageInfo^ info, _In_ Platform::String^ interfaceMemberAnchorId, _In_ Platform::String^ interfaceMemberHoloId, _In_ Platform::String^ interfaceMemberHoloTypeName, _In_ AJHoloServerPosition^ interfaceMemberPosition)
{
    auto args = ref new AJHoloServerAddHologramToAnchorCalledEventArgs(info, interfaceMemberAnchorId, interfaceMemberHoloId, interfaceMemberHoloTypeName, interfaceMemberPosition);
    AddHologramToAnchorCalled(this, args);
    return AJHoloServerAddHologramToAnchorCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<AJHoloServerRemoveHologramResult^>^ AJHoloServerServiceEventAdapter::RemoveHologramAsync(_In_ AllJoynMessageInfo^ info, _In_ Platform::String^ interfaceMemberHoloId)
{
    auto args = ref new AJHoloServerRemoveHologramCalledEventArgs(info, interfaceMemberHoloId);
    RemoveHologramCalled(this, args);
    return AJHoloServerRemoveHologramCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<AJHoloServerGetWorldAnchorResult^>^ AJHoloServerServiceEventAdapter::GetWorldAnchorAsync(_In_ AllJoynMessageInfo^ info, _In_ Platform::String^ interfaceMemberAnchorId, _In_ uint32 interfaceMemberByteIndex, _In_ uint32 interfaceMemberByteLength)
{
    auto args = ref new AJHoloServerGetWorldAnchorCalledEventArgs(info, interfaceMemberAnchorId, interfaceMemberByteIndex, interfaceMemberByteLength);
    GetWorldAnchorCalled(this, args);
    return AJHoloServerGetWorldAnchorCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<AJHoloServerGetWorldAnchorIdsResult^>^ AJHoloServerServiceEventAdapter::GetWorldAnchorIdsAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new AJHoloServerGetWorldAnchorIdsCalledEventArgs(info);
    GetWorldAnchorIdsCalled(this, args);
    return AJHoloServerGetWorldAnchorIdsCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<AJHoloServerGetHologramIdsAndNamesResult^>^ AJHoloServerServiceEventAdapter::GetHologramIdsAndNamesAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new AJHoloServerGetHologramIdsAndNamesCalledEventArgs(info);
    GetHologramIdsAndNamesCalled(this, args);
    return AJHoloServerGetHologramIdsAndNamesCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<AJHoloServerGetHologramTransformsResult^>^ AJHoloServerServiceEventAdapter::GetHologramTransformsAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new AJHoloServerGetHologramTransformsCalledEventArgs(info);
    GetHologramTransformsCalled(this, args);
    return AJHoloServerGetHologramTransformsCalledEventArgs::GetResultAsync(args);
}

// Property Reads
IAsyncOperation<AJHoloServerGetDeviceConnectedCountResult^>^ AJHoloServerServiceEventAdapter::GetDeviceConnectedCountAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new AJHoloServerGetDeviceConnectedCountRequestedEventArgs(info);
    GetDeviceConnectedCountRequested(this, args);
    return AJHoloServerGetDeviceConnectedCountRequestedEventArgs::GetResultAsync(args);
}

// Property Writes
