//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace mtaulty { namespace AJHoloServer {

// Signals
public ref class AJHoloServerWorldAnchorAddedReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property Platform::String^ AnchorId
    {
        Platform::String^ get() { return m_interfaceMemberAnchorId; }
    internal:
        void set(_In_ Platform::String^ value) { m_interfaceMemberAnchorId = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    Platform::String^ m_interfaceMemberAnchorId;
};

public ref class AJHoloServerHologramAddedReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property Platform::String^ AnchorId
    {
        Platform::String^ get() { return m_interfaceMemberAnchorId; }
    internal:
        void set(_In_ Platform::String^ value) { m_interfaceMemberAnchorId = value; }
    }
    property Platform::String^ HoloId
    {
        Platform::String^ get() { return m_interfaceMemberHoloId; }
    internal:
        void set(_In_ Platform::String^ value) { m_interfaceMemberHoloId = value; }
    }
    property Platform::String^ HoloTypeName
    {
        Platform::String^ get() { return m_interfaceMemberHoloTypeName; }
    internal:
        void set(_In_ Platform::String^ value) { m_interfaceMemberHoloTypeName = value; }
    }
    property AJHoloServerPosition^ Position
    {
        AJHoloServerPosition^ get() { return m_interfaceMemberPosition; }
    internal:
        void set(_In_ AJHoloServerPosition^ value) { m_interfaceMemberPosition = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    Platform::String^ m_interfaceMemberAnchorId;
    Platform::String^ m_interfaceMemberHoloId;
    Platform::String^ m_interfaceMemberHoloTypeName;
    AJHoloServerPosition^ m_interfaceMemberPosition;
};

public ref class AJHoloServerHologramRemovedReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property Platform::String^ HoloId
    {
        Platform::String^ get() { return m_interfaceMemberHoloId; }
    internal:
        void set(_In_ Platform::String^ value) { m_interfaceMemberHoloId = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    Platform::String^ m_interfaceMemberHoloId;
};


} } } 
