//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace mtaulty { namespace AJHoloServer {

public ref class AJHoloServerPosition sealed
{
public:
    property double Value1
    {
        double get() { return m_value1; }
        void set(double value) { m_value1 = value; }
    }
     
    property double Value2
    {
        double get() { return m_value2; }
        void set(double value) { m_value2 = value; }
    }
     
    property double Value3
    {
        double get() { return m_value3; }
        void set(double value) { m_value3 = value; }
    }
     
private:
    double m_value1;
    double m_value2;
    double m_value3;
};

public ref class AJHoloServerHoloIdsItem sealed
{
public:
    property Platform::String^ Value1
    {
        Platform::String^ get() { return m_value1; }
        void set(Platform::String^ value) { m_value1 = value; }
    }
     
    property Platform::String^ Value2
    {
        Platform::String^ get() { return m_value2; }
        void set(Platform::String^ value) { m_value2 = value; }
    }
     
    property Platform::String^ Value3
    {
        Platform::String^ get() { return m_value3; }
        void set(Platform::String^ value) { m_value3 = value; }
    }
     
private:
    Platform::String^ m_value1;
    Platform::String^ m_value2;
    Platform::String^ m_value3;
};

public ref class AJHoloServerHoloPositionsItem sealed
{
public:
    property double Value1
    {
        double get() { return m_value1; }
        void set(double value) { m_value1 = value; }
    }
     
    property double Value2
    {
        double get() { return m_value2; }
        void set(double value) { m_value2 = value; }
    }
     
    property double Value3
    {
        double get() { return m_value3; }
        void set(double value) { m_value3 = value; }
    }
     
private:
    double m_value1;
    double m_value2;
    double m_value3;
};

public ref class AllJoynMessageArgStructure sealed : Windows::Foundation::Collections::IVector<Platform::Object^>
{
public:
    AllJoynMessageArgStructure()
    {
        m_vector = ref new Platform::Collections::Vector<Platform::Object^>();
    }

    virtual Windows::Foundation::Collections::IIterator<Platform::Object^>^ First()
    {
        return m_vector->First();
    }

    virtual Platform::Object^ GetAt(unsigned int index)
    {
        return m_vector->GetAt(index);
    }

    virtual property unsigned int Size {
        virtual unsigned int get()
        {
            return m_vector->Size;
        }
    }

    virtual bool IndexOf(Platform::Object^ value, unsigned int * index)
    {
        return m_vector->IndexOf(value, index);
    }

    virtual unsigned int GetMany(unsigned int startIndex, Platform::WriteOnlyArray<Platform::Object^>^ items)
    {
        return m_vector->GetMany(startIndex, items);
    }

    virtual Windows::Foundation::Collections::IVectorView<Platform::Object^>^ GetView()
    {
        return m_vector->GetView();
    }

    virtual void SetAt(unsigned int index, Platform::Object^ value)
    {
        return m_vector->SetAt(index, value);
    }

    virtual void InsertAt(unsigned int index, Platform::Object^ value)
    {
        return m_vector->InsertAt(index, value);
    }

    virtual void Append(Platform::Object^ value)
    {
        return m_vector->Append(value);
    }

    virtual void RemoveAt(unsigned int index)
    {
        return m_vector->RemoveAt(index);
    }

    virtual void RemoveAtEnd()
    {
        return m_vector->RemoveAtEnd();
    }

    virtual void Clear()
    {
        return m_vector->Clear();
    }

    virtual void ReplaceAll(const Platform::Array<Platform::Object^>^ items)
    {
        return m_vector->ReplaceAll(items);
    }

private:
    Platform::Collections::Vector<Platform::Object^>^ m_vector;
};
} } } 

partial ref class TypeConversionHelpers
{
internal:
    static _Check_return_ int32 GetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _Out_ com::mtaulty::AJHoloServer::AJHoloServerPosition^* value)
    {
        UNREFERENCED_PARAMETER(signature);

        (*value) = ref new com::mtaulty::AJHoloServer::AJHoloServerPosition();

        alljoyn_msgarg argument1;
        alljoyn_msgarg argument2;
        alljoyn_msgarg argument3;
        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_get(argument, "(***)", &argument1, &argument2, &argument3));

        double value1;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument1, "d", &value1));
        (*value)->Value1 = value1;
        double value2;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument2, "d", &value2));
        (*value)->Value2 = value2;
        double value3;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument3, "d", &value3));
        (*value)->Value3 = value3;
        
        return ER_OK;
    }

    static _Check_return_ int32 SetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _In_ com::mtaulty::AJHoloServer::AJHoloServerPosition^ value)
    {
        UNREFERENCED_PARAMETER(signature);

        auto argument1 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument1, "d", value->Value1));
        auto argument2 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument2, "d", value->Value2));
        auto argument3 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument3, "d", value->Value3));

        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_set(argument, "(***)", argument1, argument2, argument3));
        alljoyn_msgarg_stabilize(argument);
        alljoyn_msgarg_destroy(argument1);
        alljoyn_msgarg_destroy(argument2);
        alljoyn_msgarg_destroy(argument3);

        return ER_OK;
    }

    static _Check_return_ int32 GetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _Out_ com::mtaulty::AJHoloServer::AJHoloServerHoloIdsItem^* value)
    {
        UNREFERENCED_PARAMETER(signature);

        (*value) = ref new com::mtaulty::AJHoloServer::AJHoloServerHoloIdsItem();

        alljoyn_msgarg argument1;
        alljoyn_msgarg argument2;
        alljoyn_msgarg argument3;
        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_get(argument, "(***)", &argument1, &argument2, &argument3));

        Platform::String^ value1;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument1, "s", &value1));
        (*value)->Value1 = value1;
        Platform::String^ value2;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument2, "s", &value2));
        (*value)->Value2 = value2;
        Platform::String^ value3;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument3, "s", &value3));
        (*value)->Value3 = value3;
        
        return ER_OK;
    }

    static _Check_return_ int32 SetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _In_ com::mtaulty::AJHoloServer::AJHoloServerHoloIdsItem^ value)
    {
        UNREFERENCED_PARAMETER(signature);

        auto argument1 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument1, "s", value->Value1));
        auto argument2 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument2, "s", value->Value2));
        auto argument3 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument3, "s", value->Value3));

        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_set(argument, "(***)", argument1, argument2, argument3));
        alljoyn_msgarg_stabilize(argument);
        alljoyn_msgarg_destroy(argument1);
        alljoyn_msgarg_destroy(argument2);
        alljoyn_msgarg_destroy(argument3);

        return ER_OK;
    }

    static _Check_return_ int32 GetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _Out_ com::mtaulty::AJHoloServer::AJHoloServerHoloPositionsItem^* value)
    {
        UNREFERENCED_PARAMETER(signature);

        (*value) = ref new com::mtaulty::AJHoloServer::AJHoloServerHoloPositionsItem();

        alljoyn_msgarg argument1;
        alljoyn_msgarg argument2;
        alljoyn_msgarg argument3;
        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_get(argument, "(***)", &argument1, &argument2, &argument3));

        double value1;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument1, "d", &value1));
        (*value)->Value1 = value1;
        double value2;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument2, "d", &value2));
        (*value)->Value2 = value2;
        double value3;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument3, "d", &value3));
        (*value)->Value3 = value3;
        
        return ER_OK;
    }

    static _Check_return_ int32 SetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _In_ com::mtaulty::AJHoloServer::AJHoloServerHoloPositionsItem^ value)
    {
        UNREFERENCED_PARAMETER(signature);

        auto argument1 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument1, "d", value->Value1));
        auto argument2 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument2, "d", value->Value2));
        auto argument3 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument3, "d", value->Value3));

        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_set(argument, "(***)", argument1, argument2, argument3));
        alljoyn_msgarg_stabilize(argument);
        alljoyn_msgarg_destroy(argument1);
        alljoyn_msgarg_destroy(argument2);
        alljoyn_msgarg_destroy(argument3);

        return ER_OK;
    }

};
