//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace mtaulty { namespace AJHoloServer {

public interface class IAJHoloServerService
{
public:
    // Implement this function to handle calls to the AddWorldAnchor method.
    Windows::Foundation::IAsyncOperation<AJHoloServerAddWorldAnchorResult^>^ AddWorldAnchorAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ Platform::String^ interfaceMemberAnchorId, _In_ uint32 interfaceMemberByteStart, _In_ uint32 interfaceMemberByteLength, _In_ bool interfaceMemberLastBlock, _In_ Windows::Foundation::Collections::IVectorView<byte>^ interfaceMemberAnchorData);

    // Implement this function to handle calls to the AddHologramToAnchor method.
    Windows::Foundation::IAsyncOperation<AJHoloServerAddHologramToAnchorResult^>^ AddHologramToAnchorAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ Platform::String^ interfaceMemberAnchorId, _In_ Platform::String^ interfaceMemberHoloId, _In_ Platform::String^ interfaceMemberHoloTypeName, _In_ AJHoloServerPosition^ interfaceMemberPosition);

    // Implement this function to handle calls to the RemoveHologram method.
    Windows::Foundation::IAsyncOperation<AJHoloServerRemoveHologramResult^>^ RemoveHologramAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ Platform::String^ interfaceMemberHoloId);

    // Implement this function to handle calls to the GetWorldAnchor method.
    Windows::Foundation::IAsyncOperation<AJHoloServerGetWorldAnchorResult^>^ GetWorldAnchorAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ Platform::String^ interfaceMemberAnchorId, _In_ uint32 interfaceMemberByteIndex, _In_ uint32 interfaceMemberByteLength);

    // Implement this function to handle calls to the GetWorldAnchorIds method.
    Windows::Foundation::IAsyncOperation<AJHoloServerGetWorldAnchorIdsResult^>^ GetWorldAnchorIdsAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the GetHologramIdsAndNames method.
    Windows::Foundation::IAsyncOperation<AJHoloServerGetHologramIdsAndNamesResult^>^ GetHologramIdsAndNamesAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the GetHologramTransforms method.
    Windows::Foundation::IAsyncOperation<AJHoloServerGetHologramTransformsResult^>^ GetHologramTransformsAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle requests for the value of the DeviceConnectedCount property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<AJHoloServerGetDeviceConnectedCountResult^>^ GetDeviceConnectedCountAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

};

} } } 
